name: Cache Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-b1c461d
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-b1c461d

      - name: Show cache result
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
