name: CI with Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prime-cache-b1c461d
        id: cache
        uses: actions/cache@v4
        with:
          # single-string path is less error-prone in YAML
          path: ~/.cache/mydeps
          key: cache-b1c461d

      - name: Report cache status
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: |
          echo "Cache hit: $CACHE_HIT"
