name: Email Step Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f3002461@ds.study.iitm.ac.in
        run: echo "Hello from 23f3002461@ds.study.iitm.ac.in"
